"""Add Feedback

Revision ID: 77a15ee6927c
Revises: 07c199ba3a01
Create Date: 2026-08-20 10:48:26.896534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a15ee6927c'
down_revision: Union[str, Sequence[str], None] = '07c199ba3a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_feedback',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('owner_external_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('owner_external_id', 'message_id', name='uq_owner_message')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_feedback')
    # ### end Alembic commands ###
